package defpackage;


// Code generated by colf(1); DO NOT EDIT.


import androidx.annotation.Keep;

import java.io.Serializable;


/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
@Keep
public class ASER implements Serializable {


    public String form;

    public String model;

    public String os;

    public String api;

    public String uid;

    public String IP;

    public String ver;

    public String usid;

    public String errortype;

    public String dataerr;


    /**
     * Default constructor
     */
    public ASER() {
        init();
    }


    /**
     * Colfer zero values.
     */
    private void init() {
        form = "";
        model = "";
        os = "";
        api = "";
        uid = "";
        IP = "";
        ver = "";
        usid = "";
        errortype = "";
        dataerr = "";
    }
}
