package defpackage;


// Code generated by colf(1); DO NOT EDIT.


import androidx.annotation.Keep;

import java.io.Serializable;


/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
@Keep
public class ASRC implements Serializable {


    public String by;

    public short rnd;

    public String form;

    public String model;

    public String os;

    public String api;

    public String uid;

    public String IP;

    public String regcode;

    public String mobile;

    public String vrfcode;


    /**
     * Default constructor
     */
    public ASRC() {
        init();
    }


    /**
     * Colfer zero values.
     */
    private void init() {
        by = "";
        form = "";
        model = "";
        os = "";
        api = "";
        uid = "";
        IP = "";
        regcode = "";
        mobile = "";
        vrfcode = "";
    }
}
