package defpackage;


// Code generated by colf(1); DO NOT EDIT.


import androidx.annotation.Keep;

import java.io.Serializable;


/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
@Keep
public class ASRM implements Serializable {


    public short rnd;

    public String form;

    public String model;

    public String os;

    public String api;

    public String uid;

    public String IP;

    public String Regcode;

    public String mobile;

    public String utype;

    public String imsi1;

    public String imsi2;

    public String mcc1;

    public String mcc2;


    /**
     * Default constructor
     */
    public ASRM() {
        init();
    }


    /**
     * Colfer zero values.
     */
    private void init() {
        form = "";
        model = "";
        os = "";
        api = "";
        uid = "";
        IP = "";
        Regcode = "";
        mobile = "";
        utype = "";
        imsi1 = "";
        imsi2 = "";
        mcc1 = "";
        mcc2 = "";
    }
}
