package defpackage;


// Code generated by colf(1); DO NOT EDIT.


import androidx.annotation.Keep;

import java.io.Serializable;


/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
@Keep
public class SMNG implements Serializable {


    public String c;

    public double glon;

    public double glat;


    /**
     * Default constructor
     */
    public SMNG() {
        init();
    }


    /**
     * Colfer zero values.
     */
    private void init() {
        c = "";
    }
}
