package domain.shadowss.model.marshal;


// Code generated by colf(1); DO NOT EDIT.


import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamException;
import java.io.OutputStream;
import java.io.Serializable;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.nio.charset.StandardCharsets;
import java.util.InputMismatchException;

import static java.lang.String.format;


/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
@javax.annotation.Generated(value = "colf(1)", comments = "Colfer from schema file structdef.colf")
public class ASRM implements Serializable {

    /**
     * The upper limit for serial byte sizes.
     */
    public static int colferSizeMax = 16 * 1024 * 1024;


    public short rnd;

    public String form;

    public String model;

    public String os;

    public String api;

    public String uid;

    public String IP;

    public String Regcode;

    public String mobile;

    public String utype;

    public String imsi1;

    public String imsi2;

    public String mcc1;

    public String mcc2;


    /**
     * Default constructor
     */
    public ASRM() {
        init();
    }


    /**
     * Colfer zero values.
     */
    private void init() {
        form = "";
        model = "";
        os = "";
        api = "";
        uid = "";
        IP = "";
        Regcode = "";
        mobile = "";
        utype = "";
        imsi1 = "";
        imsi2 = "";
        mcc1 = "";
        mcc2 = "";
    }

    /**
     * {@link #reset(InputStream) Reusable} deserialization of Colfer streams.
     */
    public static class Unmarshaller {

        /**
         * The data source.
         */
        protected InputStream in;

        /**
         * The read buffer.
         */
        public byte[] buf;

        /**
         * The {@link #buf buffer}'s data start index, inclusive.
         */
        protected int offset;

        /**
         * The {@link #buf buffer}'s data end index, exclusive.
         */
        protected int i;


        /**
         * @param in  the data source or {@code null}.
         * @param buf the initial buffer or {@code null}.
         */
        public Unmarshaller(InputStream in, byte[] buf) {
            // TODO: better size estimation
            if (buf == null || buf.length == 0)
                buf = new byte[Math.min(ASRM.colferSizeMax, 2048)];
            this.buf = buf;
            reset(in);
        }

        /**
         * Reuses the marshaller.
         *
         * @param in the data source or {@code null}.
         * @throws IllegalStateException on pending data.
         */
        public void reset(InputStream in) {
            if (this.i != this.offset) throw new IllegalStateException("colfer: pending data");
            this.in = in;
            this.offset = 0;
            this.i = 0;
        }

        /**
         * Deserializes the following object.
         *
         * @return the result or {@code null} when EOF.
         * @throws IOException            from the input stream.
         * @throws SecurityException      on an upper limit breach defined by {@link #colferSizeMax}.
         * @throws InputMismatchException when the data does not match this object's schema.
         */
        public ASRM next() throws IOException {
            if (in == null) return null;

            while (true) {
                if (this.i > this.offset) {
                    try {
                        ASRM o = new ASRM();
                        this.offset = o.unmarshal(this.buf, this.offset, this.i);
                        return o;
                    } catch (BufferUnderflowException e) {
                    }
                }
                // not enough data

                if (this.i <= this.offset) {
                    this.offset = 0;
                    this.i = 0;
                } else if (i == buf.length) {
                    byte[] src = this.buf;
                    // TODO: better size estimation
                    if (offset == 0)
                        this.buf = new byte[Math.min(ASRM.colferSizeMax, this.buf.length * 4)];
                    System.arraycopy(src, this.offset, this.buf, 0, this.i - this.offset);
                    this.i -= this.offset;
                    this.offset = 0;
                }
                assert this.i < this.buf.length;

                int n = in.read(buf, i, buf.length - i);
                if (n < 0) {
                    if (this.i > this.offset)
                        throw new InputMismatchException("colfer: pending data with EOF");
                    return null;
                }
                assert n > 0;
                i += n;
            }
        }

    }


    /**
     * Serializes the object.
     *
     * @param out the data destination.
     * @param buf the initial buffer or {@code null}.
     * @return the final buffer. When the serial fits into {@code buf} then the return is {@code buf}.
     * Otherwise the return is a new buffer, large enough to hold the whole serial.
     * @throws IOException           from {@code out}.
     * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
     */
    public byte[] marshal(OutputStream out, byte[] buf) throws IOException {
        // TODO: better size estimation
        if (buf == null || buf.length == 0)
            buf = new byte[Math.min(ASRM.colferSizeMax, 2048)];

        while (true) {
            int i;
            try {
                i = marshal(buf, 0);
            } catch (BufferOverflowException e) {
                buf = new byte[Math.min(ASRM.colferSizeMax, buf.length * 4)];
                continue;
            }

            out.write(buf, 0, i);
            return buf;
        }
    }

    /**
     * Serializes the object.
     *
     * @param buf    the data destination.
     * @param offset the initial index for {@code buf}, inclusive.
     * @return the final index for {@code buf}, exclusive.
     * @throws BufferOverflowException when {@code buf} is too small.
     * @throws IllegalStateException   on an upper limit breach defined by {@link #colferSizeMax}.
     */
    public int marshal(byte[] buf, int offset) {
        int i = offset;

        try {
            if (this.rnd != 0) {
                short x = this.rnd;
                if ((x & (short) 0xff00) != 0) {
                    buf[i++] = (byte) 0;
                    buf[i++] = (byte) (x >>> 8);
                } else {
                    buf[i++] = (byte) (0 | 0x80);
                }
                buf[i++] = (byte) x;
            }

            if (!this.form.isEmpty()) {
                buf[i++] = (byte) 1;
                int start = ++i;

                String s = this.form;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.form size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            if (!this.model.isEmpty()) {
                buf[i++] = (byte) 2;
                int start = ++i;

                String s = this.model;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.model size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            if (!this.os.isEmpty()) {
                buf[i++] = (byte) 3;
                int start = ++i;

                String s = this.os;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.os size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            if (!this.api.isEmpty()) {
                buf[i++] = (byte) 4;
                int start = ++i;

                String s = this.api;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.api size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            if (!this.uid.isEmpty()) {
                buf[i++] = (byte) 5;
                int start = ++i;

                String s = this.uid;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.uid size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            if (!this.IP.isEmpty()) {
                buf[i++] = (byte) 6;
                int start = ++i;

                String s = this.IP;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.IP size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            if (!this.Regcode.isEmpty()) {
                buf[i++] = (byte) 7;
                int start = ++i;

                String s = this.Regcode;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.Regcode size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            if (!this.mobile.isEmpty()) {
                buf[i++] = (byte) 8;
                int start = ++i;

                String s = this.mobile;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.mobile size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            if (!this.utype.isEmpty()) {
                buf[i++] = (byte) 9;
                int start = ++i;

                String s = this.utype;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.utype size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            if (!this.imsi1.isEmpty()) {
                buf[i++] = (byte) 10;
                int start = ++i;

                String s = this.imsi1;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.imsi1 size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            if (!this.imsi2.isEmpty()) {
                buf[i++] = (byte) 11;
                int start = ++i;

                String s = this.imsi2;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.imsi2 size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            if (!this.mcc1.isEmpty()) {
                buf[i++] = (byte) 12;
                int start = ++i;

                String s = this.mcc1;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.mcc1 size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            if (!this.mcc2.isEmpty()) {
                buf[i++] = (byte) 13;
                int start = ++i;

                String s = this.mcc2;
                for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
                    char c = s.charAt(sIndex);
                    if (c < '\u0080') {
                        buf[i++] = (byte) c;
                    } else if (c < '\u0800') {
                        buf[i++] = (byte) (192 | c >>> 6);
                        buf[i++] = (byte) (128 | c & 63);
                    } else if (c < '\ud800' || c > '\udfff') {
                        buf[i++] = (byte) (224 | c >>> 12);
                        buf[i++] = (byte) (128 | c >>> 6 & 63);
                        buf[i++] = (byte) (128 | c & 63);
                    } else {
                        int cp = 0;
                        if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
                        if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                            buf[i++] = (byte) (240 | cp >>> 18);
                            buf[i++] = (byte) (128 | cp >>> 12 & 63);
                            buf[i++] = (byte) (128 | cp >>> 6 & 63);
                            buf[i++] = (byte) (128 | cp & 63);
                        } else
                            buf[i++] = (byte) '?';
                    }
                }
                int size = i - start;
                if (size > ASRM.colferSizeMax)
                    throw new IllegalStateException(format("colfer: main.ASRM.mcc2 size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int ii = start - 1;
                if (size > 0x7f) {
                    i++;
                    for (int x = size; x >= 1 << 14; x >>>= 7) i++;
                    System.arraycopy(buf, start, buf, i - size, size);

                    do {
                        buf[ii++] = (byte) (size | 0x80);
                        size >>>= 7;
                    } while (size > 0x7f);
                }
                buf[ii] = (byte) size;
            }

            buf[i++] = (byte) 0x7f;
            return i;
        } catch (ArrayIndexOutOfBoundsException e) {
            if (i - offset > ASRM.colferSizeMax)
                throw new IllegalStateException(format("colfer: main.ASRM exceeds %d bytes", ASRM.colferSizeMax));
            if (i > buf.length) throw new BufferOverflowException();
            throw e;
        }
    }

    /**
     * Deserializes the object.
     *
     * @param buf    the data source.
     * @param offset the initial index for {@code buf}, inclusive.
     * @return the final index for {@code buf}, exclusive.
     * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
     * @throws SecurityException        on an upper limit breach defined by {@link #colferSizeMax}.
     * @throws InputMismatchException   when the data does not match this object's schema.
     */
    public int unmarshal(byte[] buf, int offset) {
        return unmarshal(buf, offset, buf.length);
    }

    /**
     * Deserializes the object.
     *
     * @param buf    the data source.
     * @param offset the initial index for {@code buf}, inclusive.
     * @param end    the index limit for {@code buf}, exclusive.
     * @return the final index for {@code buf}, exclusive.
     * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
     * @throws SecurityException        on an upper limit breach defined by {@link #colferSizeMax}.
     * @throws InputMismatchException   when the data does not match this object's schema.
     */
    public int unmarshal(byte[] buf, int offset, int end) {
        if (end > buf.length) end = buf.length;
        int i = offset;

        try {
            byte header = buf[i++];

            if (header == (byte) 0) {
                this.rnd = (short) ((buf[i++] & 0xff) << 8 | (buf[i++] & 0xff));
                header = buf[i++];
            } else if (header == (byte) (0 | 0x80)) {
                this.rnd = (short) (buf[i++] & 0xff);
                header = buf[i++];
            }

            if (header == (byte) 1) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.form size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.form = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header == (byte) 2) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.model size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.model = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header == (byte) 3) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.os size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.os = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header == (byte) 4) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.api size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.api = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header == (byte) 5) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.uid size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.uid = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header == (byte) 6) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.IP size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.IP = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header == (byte) 7) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.Regcode size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.Regcode = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header == (byte) 8) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.mobile size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.mobile = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header == (byte) 9) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.utype size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.utype = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header == (byte) 10) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.imsi1 size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.imsi1 = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header == (byte) 11) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.imsi2 size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.imsi2 = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header == (byte) 12) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.mcc1 size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.mcc1 = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header == (byte) 13) {
                int size = 0;
                for (int shift = 0; true; shift += 7) {
                    byte b = buf[i++];
                    size |= (b & 0x7f) << shift;
                    if (shift == 28 || b >= 0) break;
                }
                if (size < 0 || size > ASRM.colferSizeMax)
                    throw new SecurityException(format("colfer: main.ASRM.mcc2 size %d exceeds %d UTF-8 bytes", size, ASRM.colferSizeMax));

                int start = i;
                i += size;
                this.mcc2 = new String(buf, start, size, StandardCharsets.UTF_8);
                header = buf[i++];
            }

            if (header != (byte) 0x7f)
                throw new InputMismatchException(format("colfer: unknown header at byte %d", i - 1));
        } finally {
            if (i > end && end - offset < ASRM.colferSizeMax) throw new BufferUnderflowException();
            if (i < 0 || i - offset > ASRM.colferSizeMax)
                throw new SecurityException(format("colfer: main.ASRM exceeds %d bytes", ASRM.colferSizeMax));
            if (i > end) throw new BufferUnderflowException();
        }

        return i;
    }

    // {@link Serializable} version number.
    private static final long serialVersionUID = 14L;

    // {@link Serializable} Colfer extension.
    private void writeObject(ObjectOutputStream out) throws IOException {
        // TODO: better size estimation
        byte[] buf = new byte[1024];
        int n;
        while (true) try {
            n = marshal(buf, 0);
            break;
        } catch (BufferUnderflowException e) {
            buf = new byte[4 * buf.length];
        }

        out.writeInt(n);
        out.write(buf, 0, n);
    }

    // {@link Serializable} Colfer extension.
    private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
        init();

        int n = in.readInt();
        byte[] buf = new byte[n];
        in.readFully(buf);
        unmarshal(buf, 0);
    }

    // {@link Serializable} Colfer extension.
    private void readObjectNoData() throws ObjectStreamException {
        init();
    }

    /**
     * Gets main.ASRM.rnd.
     *
     * @return the value.
     */
    public short getRnd() {
        return this.rnd;
    }

    /**
     * Sets main.ASRM.rnd.
     *
     * @param value the replacement.
     */
    public void setRnd(short value) {
        this.rnd = value;
    }

    /**
     * Sets main.ASRM.rnd.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withRnd(short value) {
        this.rnd = value;
        return this;
    }

    /**
     * Gets main.ASRM.form.
     *
     * @return the value.
     */
    public String getForm() {
        return this.form;
    }

    /**
     * Sets main.ASRM.form.
     *
     * @param value the replacement.
     */
    public void setForm(String value) {
        this.form = value;
    }

    /**
     * Sets main.ASRM.form.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withForm(String value) {
        this.form = value;
        return this;
    }

    /**
     * Gets main.ASRM.model.
     *
     * @return the value.
     */
    public String getModel() {
        return this.model;
    }

    /**
     * Sets main.ASRM.model.
     *
     * @param value the replacement.
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Sets main.ASRM.model.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withModel(String value) {
        this.model = value;
        return this;
    }

    /**
     * Gets main.ASRM.os.
     *
     * @return the value.
     */
    public String getOs() {
        return this.os;
    }

    /**
     * Sets main.ASRM.os.
     *
     * @param value the replacement.
     */
    public void setOs(String value) {
        this.os = value;
    }

    /**
     * Sets main.ASRM.os.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withOs(String value) {
        this.os = value;
        return this;
    }

    /**
     * Gets main.ASRM.api.
     *
     * @return the value.
     */
    public String getApi() {
        return this.api;
    }

    /**
     * Sets main.ASRM.api.
     *
     * @param value the replacement.
     */
    public void setApi(String value) {
        this.api = value;
    }

    /**
     * Sets main.ASRM.api.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withApi(String value) {
        this.api = value;
        return this;
    }

    /**
     * Gets main.ASRM.uid.
     *
     * @return the value.
     */
    public String getUid() {
        return this.uid;
    }

    /**
     * Sets main.ASRM.uid.
     *
     * @param value the replacement.
     */
    public void setUid(String value) {
        this.uid = value;
    }

    /**
     * Sets main.ASRM.uid.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withUid(String value) {
        this.uid = value;
        return this;
    }

    /**
     * Gets main.ASRM.IP.
     *
     * @return the value.
     */
    public String getIP() {
        return this.IP;
    }

    /**
     * Sets main.ASRM.IP.
     *
     * @param value the replacement.
     */
    public void setIP(String value) {
        this.IP = value;
    }

    /**
     * Sets main.ASRM.IP.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withIP(String value) {
        this.IP = value;
        return this;
    }

    /**
     * Gets main.ASRM.Regcode.
     *
     * @return the value.
     */
    public String getRegcode() {
        return this.Regcode;
    }

    /**
     * Sets main.ASRM.Regcode.
     *
     * @param value the replacement.
     */
    public void setRegcode(String value) {
        this.Regcode = value;
    }

    /**
     * Sets main.ASRM.Regcode.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withRegcode(String value) {
        this.Regcode = value;
        return this;
    }

    /**
     * Gets main.ASRM.mobile.
     *
     * @return the value.
     */
    public String getMobile() {
        return this.mobile;
    }

    /**
     * Sets main.ASRM.mobile.
     *
     * @param value the replacement.
     */
    public void setMobile(String value) {
        this.mobile = value;
    }

    /**
     * Sets main.ASRM.mobile.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withMobile(String value) {
        this.mobile = value;
        return this;
    }

    /**
     * Gets main.ASRM.utype.
     *
     * @return the value.
     */
    public String getUtype() {
        return this.utype;
    }

    /**
     * Sets main.ASRM.utype.
     *
     * @param value the replacement.
     */
    public void setUtype(String value) {
        this.utype = value;
    }

    /**
     * Sets main.ASRM.utype.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withUtype(String value) {
        this.utype = value;
        return this;
    }

    /**
     * Gets main.ASRM.imsi1.
     *
     * @return the value.
     */
    public String getImsi1() {
        return this.imsi1;
    }

    /**
     * Sets main.ASRM.imsi1.
     *
     * @param value the replacement.
     */
    public void setImsi1(String value) {
        this.imsi1 = value;
    }

    /**
     * Sets main.ASRM.imsi1.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withImsi1(String value) {
        this.imsi1 = value;
        return this;
    }

    /**
     * Gets main.ASRM.imsi2.
     *
     * @return the value.
     */
    public String getImsi2() {
        return this.imsi2;
    }

    /**
     * Sets main.ASRM.imsi2.
     *
     * @param value the replacement.
     */
    public void setImsi2(String value) {
        this.imsi2 = value;
    }

    /**
     * Sets main.ASRM.imsi2.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withImsi2(String value) {
        this.imsi2 = value;
        return this;
    }

    /**
     * Gets main.ASRM.mcc1.
     *
     * @return the value.
     */
    public String getMcc1() {
        return this.mcc1;
    }

    /**
     * Sets main.ASRM.mcc1.
     *
     * @param value the replacement.
     */
    public void setMcc1(String value) {
        this.mcc1 = value;
    }

    /**
     * Sets main.ASRM.mcc1.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withMcc1(String value) {
        this.mcc1 = value;
        return this;
    }

    /**
     * Gets main.ASRM.mcc2.
     *
     * @return the value.
     */
    public String getMcc2() {
        return this.mcc2;
    }

    /**
     * Sets main.ASRM.mcc2.
     *
     * @param value the replacement.
     */
    public void setMcc2(String value) {
        this.mcc2 = value;
    }

    /**
     * Sets main.ASRM.mcc2.
     *
     * @param value the replacement.
     * @return {link this}.
     */
    public ASRM withMcc2(String value) {
        this.mcc2 = value;
        return this;
    }

    @Override
    public final int hashCode() {
        int h = 1;
        h = 31 * h + (this.rnd & 0xffff);
        if (this.form != null) h = 31 * h + this.form.hashCode();
        if (this.model != null) h = 31 * h + this.model.hashCode();
        if (this.os != null) h = 31 * h + this.os.hashCode();
        if (this.api != null) h = 31 * h + this.api.hashCode();
        if (this.uid != null) h = 31 * h + this.uid.hashCode();
        if (this.IP != null) h = 31 * h + this.IP.hashCode();
        if (this.Regcode != null) h = 31 * h + this.Regcode.hashCode();
        if (this.mobile != null) h = 31 * h + this.mobile.hashCode();
        if (this.utype != null) h = 31 * h + this.utype.hashCode();
        if (this.imsi1 != null) h = 31 * h + this.imsi1.hashCode();
        if (this.imsi2 != null) h = 31 * h + this.imsi2.hashCode();
        if (this.mcc1 != null) h = 31 * h + this.mcc1.hashCode();
        if (this.mcc2 != null) h = 31 * h + this.mcc2.hashCode();
        return h;
    }

    @Override
    public final boolean equals(Object o) {
        return o instanceof ASRM && equals((ASRM) o);
    }

    public final boolean equals(ASRM o) {
        if (o == null) return false;
        if (o == this) return true;
        return o.getClass() == ASRM.class
                && this.rnd == o.rnd
                && (this.form == null ? o.form == null : this.form.equals(o.form))
                && (this.model == null ? o.model == null : this.model.equals(o.model))
                && (this.os == null ? o.os == null : this.os.equals(o.os))
                && (this.api == null ? o.api == null : this.api.equals(o.api))
                && (this.uid == null ? o.uid == null : this.uid.equals(o.uid))
                && (this.IP == null ? o.IP == null : this.IP.equals(o.IP))
                && (this.Regcode == null ? o.Regcode == null : this.Regcode.equals(o.Regcode))
                && (this.mobile == null ? o.mobile == null : this.mobile.equals(o.mobile))
                && (this.utype == null ? o.utype == null : this.utype.equals(o.utype))
                && (this.imsi1 == null ? o.imsi1 == null : this.imsi1.equals(o.imsi1))
                && (this.imsi2 == null ? o.imsi2 == null : this.imsi2.equals(o.imsi2))
                && (this.mcc1 == null ? o.mcc1 == null : this.mcc1.equals(o.mcc1))
                && (this.mcc2 == null ? o.mcc2 == null : this.mcc2.equals(o.mcc2));
    }

}
