package defpackage.shadowss.jbit;


// Code generated by colf(1); DO NOT EDIT.


import java.io.Serializable;


/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class ASAU implements Serializable {


    public String token;

    public long time;

    public float timezone;


    /**
     * Default constructor
     */
    public ASAU() {
        init();
    }


    /**
     * Colfer zero values.
     */
    private void init() {
        token = "";
    }
}
