package defpackage.shadowss.jbit;


// Code generated by colf(1); DO NOT EDIT.


import java.io.Serializable;


/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class ASRR implements Serializable {


    public short rnd;

    public String form;

    public String model;

    public String os;

    public String api;

    public String uid;

    public String IP;

    public String mcc1;

    public String mcc2;

    public String lang;


    /**
     * Default constructor
     */
    public ASRR() {
        init();
    }


    /**
     * Colfer zero values.
     */
    private void init() {
        form = "";
        model = "";
        os = "";
        api = "";
        uid = "";
        IP = "";
        mcc1 = "";
        mcc2 = "";
        lang = "";
    }
}
