package defpackage.shadowss.jbit;


// Code generated by colf(1); DO NOT EDIT.


import java.io.Serializable;


/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class RGI1Data implements Serializable {


    public String country;

    public String regcode;

    public byte min;

    public byte max;

    public String numex;


    /**
     * Default constructor
     */
    public RGI1Data() {
        init();
    }


    /**
     * Colfer zero values.
     */
    private void init() {
        country = "";
        regcode = "";
        numex = "";
    }
}
