package defpackage.shadowss.jbit;


// Code generated by colf(1); DO NOT EDIT.


import java.io.Serializable;


/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class SAPO implements Serializable {


    public short rnd;


    /**
     * Default constructor
     */
    public SAPO() {
        init();
    }


    /**
     * Colfer zero values.
     */
    private void init() {
    }
}
