package defpackage.shadowss.jbit;


// Code generated by colf(1); DO NOT EDIT.


import java.io.Serializable;


/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class SARM implements Serializable {


    public short rnd;

    public String form;

    public String error;

    public String dataerr;

    public String usid;

    public String token;


    /**
     * Default constructor
     */
    public SARM() {
        init();
    }


    /**
     * Colfer zero values.
     */
    private void init() {
        form = "";
        error = "";
        dataerr = "";
        usid = "";
        token = "";
    }
}
