package defpackage.shadowss.jbit;


// Code generated by colf(1); DO NOT EDIT.


import java.io.Serializable;


/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class SARR implements Serializable {


    private static final RGI1Data[] _zeroData = new RGI1Data[0];
    public short rnd;
    public String form;
    public String error;
    public String dataerr;
    public RGI1Data[] data;

    /**
     * Default constructor
     */
    public SARR() {
        init();
    }

    /**
     * Colfer zero values.
     */
    private void init() {
        form = "";
        error = "";
        dataerr = "";
        data = _zeroData;
    }

}
